#include "nsISupports.idl"
#include "nsIObserver.idl"

[scriptable,uuid(0960cf50-d196-11da-a94d-0800200c9a66)]
interface nsIRTSE:nsISupports
{
	attribute string version;
	void    prefsRegisterObserver(in string aPref,in nsIObserver aFunc);
	void    prefsUnregisterObserver(in string aPref,in nsIObserver aFunc);
	void    prefsSetBool(in string aName,in string aValue,in string aRoot);
	void    prefsSetString(in string aName,in string aValue,in string aRoot);
	boolean prefsGetBool(in string aName,in string aRoot);
	string  prefsGetString(in string aName,in string aRoot);
};
